//+------------------------------------------------------------------+
//|                                                   ORB Strategy   |
//|                    Opening Range Breakout (MT5 Expert Advisor)  |
//| Features: Multi-session (NY/London) with local-time inputs,     |
//| risk-based sizing, RR targets, daily/overall DD halts, filters, |
//| ATR trailing, breakeven, cooldown, stats panel, ORB lines,      |
//| alerts.                                                          |
//+------------------------------------------------------------------+
#property copyright   "Generated by ORB EA Generator"
#property version     "1.0.0"
#property strict

#include <Trade/Trade.mqh>

//====================================================================
// Inputs
//====================================================================
input bool   InpEnableNewYorkSession          = true;        // Enable New York session
input string InpNewYorkRangeStartLocal        = "09:30";     // New York opening range start (Local NY time)
input string InpNewYorkRangeEndLocal          = "10:00";     // New York opening range end (Local NY time)
input string InpNewYorkCutoffLocal            = "";          // New York trading cutoff time (Local NY time); empty disables
input string InpNewYorkTradeStartLocal        = "";          // New York trading start time (Local NY time); empty uses range end

input bool   InpEnableLondonSession           = false;       // Enable London session
input string InpLondonRangeStartLocal         = "07:30";     // London opening range start (Local London time)
input string InpLondonRangeEndLocal           = "08:00";     // London opening range end (Local London time)
input string InpLondonCutoffLocal             = "";          // London trading cutoff time (Local London time); empty disables
input string InpLondonTradeStartLocal         = "";          // London trading start time (Local London time); empty uses range end

// Risk Management
input double InpRiskPerTradePercent           = 1.0;         // Risk per trade (% of equity)
input double InpRiskRewardRatio               = 2.0;         // Risk-Reward ratio (TP = SL * RR)
input int    InpMaxTradesPerSession           = 1;           // Max trades per session per day
input double InpMaxStopLossPips               = 150.0;       // Maximum stop loss (pips); trades skipped if exceeded
input double InpDailyDrawdownPercent          = 5.0;         // Daily drawdown limit (%) to halt trading
input double InpOverallDrawdownPercent        = 25.0;        // Overall drawdown limit (%) from initial equity

// Entry Filters
input double InpMaxORBWidthPips               = 50.0;        // Skip if ORB width exceeds (pips). 0 disables
input double InpMinBreakoutDistancePips       = 1.0;         // Minimum breakout distance beyond ORB (pips)
input ENUM_TIMEFRAMES InpTrendTF              = PERIOD_D1;   // Trend filter timeframe
input int    InpMAPeriod                      = 200;         // Moving Average period for trend filter
input ENUM_MA_METHOD InpMAMethod              = MODE_SMA;    // Moving Average method
input ENUM_APPLIED_PRICE InpMAPrice           = PRICE_CLOSE; // Applied price for MA
input bool   InpVolumeConfirmation            = true;        // Require current tick volume > previous bar
input int    InpCooldownMinutes               = 30;          // Cooldown period after trade (minutes)

// Trade Management
input double InpBreakevenAfterR               = 1.0;         // Move SL to BE after this R achieved (0 disables)
input int    InpATRPeriod                     = 14;          // ATR period for trailing
input double InpATRMultiplier                 = 2.0;         // ATR multiplier for trailing stop
input double InpTrailStartAfterR              = 1.0;         // Start trailing after this R (can be >= BE)
input ENUM_TIMEFRAMES InpATRTimeframe         = PERIOD_M5;   // ATR timeframe

// Symbol and Execution
input ulong  InpMagicNumber                   = 105012345;   // Magic number
input int    InpSlippagePoints                = 5;           // Slippage (points)
input bool   InpAllowShorts                   = true;        // Allow short trades
input bool   InpAllowLongs                    = true;        // Allow long trades

// Visualization & Alerts
input bool   InpShowPanel                     = true;        // Show stats panel
input bool   InpShowORBLevels                 = true;        // Draw ORB levels
input color  InpColorORBHighNY                = clrLime;     // ORB High NY color
input color  InpColorORBLowNY                 = clrRed;      // ORB Low NY color
input color  InpColorORBHighLondon            = clrAqua;     // ORB High London color
input color  InpColorORBLowLondon             = clrTomato;   // ORB Low London color
input bool   InpEnableAlerts                  = true;        // Enable alerts

//====================================================================
// Globals
//====================================================================
CTrade trade;

datetime g_lastDayServer = 0;
double   g_initialEquity = 0.0;
double   g_todayPeakEquity = 0.0;
double   g_todayMinEquity = DBL_MAX;
bool     g_dailyHalt = false;
bool     g_overallHalt = false;

// Session state (per day)
struct SessionState
{
	bool     orbComputed;
	datetime sessionStart;
	datetime sessionEnd;
	datetime cutoffTime;
	datetime tradeStartTime;
	double   orbHigh;
	double   orbLow;
	int      tradesTaken;
	datetime lastTradeTime;
};

SessionState g_stateNY;
SessionState g_stateLondon;

//====================================================================
// Utilities: Time & Timezone helpers
//====================================================================
int GetServerUtcOffsetSeconds()
{
	datetime nowServer = TimeCurrent();
	datetime nowGmt    = TimeGMT();
	return (int)(nowServer - nowGmt);
}

MqlDateTime ToDateStruct(datetime t)
{
	MqlDateTime st; TimeToStruct(t, st); return st;
}

datetime FromDateParts(int year, int mon, int day, int hour, int min, int sec)
{
	MqlDateTime dt; ZeroMemory(dt);
	dt.year = year; dt.mon = mon; dt.day = day; dt.hour = hour; dt.min = min; dt.sec = sec;
	return StructToTime(dt);
}

int DayOfWeek(datetime t)
{
	MqlDateTime s = ToDateStruct(t);
    return s.day_of_week; // 0=Sunday ... 6=Saturday
}

int GetNthWeekdayOfMonth(int year, int month, int weekday, int nth)
{
    // Returns the day-of-month for the nth weekday (e.g., 2nd Sunday) in given month
    // weekday: 0=Sunday..6=Saturday
    MqlDateTime dt; ZeroMemory(dt);
    dt.year = year; dt.mon = month; dt.day = 1; dt.hour = 0; dt.min = 0; dt.sec = 0;
    datetime t = StructToTime(dt);
    int dow = DayOfWeek(t);
    int delta = weekday - dow; if(delta < 0) delta += 7;
    int firstWeekdayDay = 1 + delta;
    int target = firstWeekdayDay + (nth - 1) * 7;
    return target;
}

int GetLastWeekdayOfMonth(int year, int month, int weekday)
{
    // Returns the day-of-month for the last weekday (e.g., last Sunday) in given month
    // Find first day of next month, go back 1 day, then walk back to weekday
    int nextMonth = month == 12 ? 1 : month + 1;
    int nextYear  = month == 12 ? year + 1 : year;
    datetime firstNext = FromDateParts(nextYear, nextMonth, 1, 0, 0, 0);
    datetime lastDay = firstNext - 24*60*60;
    int dow = DayOfWeek(lastDay);
    int delta = dow - weekday; if(delta < 0) delta += 7;
    MqlDateTime lastDt = ToDateStruct(lastDay);
    return lastDt.day - delta;
}

bool IsNYDST(datetime anyUtc)
{
    // US DST: starts 2nd Sunday in March, ends 1st Sunday in November, at 02:00 local
    MqlDateTime utc = ToDateStruct(anyUtc);
    int year = utc.year;
    // Approx local dates; we compare by local date, but we can approximate by UTC date since we only need the day range
    int marchSecondSunday = GetNthWeekdayOfMonth(year, 3, 0, 2);   // Sunday=0
    int novFirstSunday    = GetNthWeekdayOfMonth(year, 11, 0, 1);
    datetime dstStartLocal = FromDateParts(year, 3, marchSecondSunday, 2, 0, 0); // 02:00 local
    datetime dstEndLocal   = FromDateParts(year, 11, novFirstSunday, 2, 0, 0);   // 02:00 local
    // Assume EST=UTC-5 before DST and EDT=UTC-4 during DST. For boundary approximation, compare by local nominal.
    // Convert these local times to UTC by subtracting standard offsets:
    datetime dstStartUtcApprox = dstStartLocal + 5*60*60; // 02:00 local -> 07:00 UTC approx at transition
    datetime dstEndUtcApprox   = dstEndLocal   + 4*60*60; // 02:00 local -> 06:00 UTC approx at transition
    return (anyUtc >= dstStartUtcApprox && anyUtc < dstEndUtcApprox);
}

bool IsLondonDST(datetime anyUtc)
{
    // UK DST: starts last Sunday in March at 01:00 UTC, ends last Sunday in October at 01:00 UTC
    MqlDateTime utc = ToDateStruct(anyUtc);
    int year = utc.year;
    int marchLastSunday = GetLastWeekdayOfMonth(year, 3, 0); // Sunday=0
    int octLastSunday   = GetLastWeekdayOfMonth(year, 10, 0);
    datetime startUtc = FromDateParts(year, 3, marchLastSunday, 1, 0, 0);
    datetime endUtc   = FromDateParts(year, 10, octLastSunday, 1, 0, 0);
    return (anyUtc >= startUtc && anyUtc < endUtc);
}

int GetNYUtcOffsetSecondsAt(datetime anyUtc)
{
    return IsNYDST(anyUtc) ? -4*60*60 : -5*60*60;
}

int GetLondonUtcOffsetSecondsAt(datetime anyUtc)
{
    return IsLondonDST(anyUtc) ? +1*60*60 : 0;
}

bool ParseHHMM(const string hhmm, int &hourOut, int &minOut)
{
    int p = StringFind(hhmm, ":");
    if(p <= 0) return false;
    string hs = StringSubstr(hhmm, 0, p);
    string ms = StringSubstr(hhmm, p+1);
    hourOut = (int)StringToInteger(hs);
    minOut  = (int)StringToInteger(ms);
    if(hourOut < 0 || hourOut > 23 || minOut < 0 || minOut > 59) return false;
    return true;
}

datetime RegionLocalTodayToServerTime(bool isNY, int localHour, int localMin)
{
    // Determine region's current local date, build timestamp at given local time, convert to server time
    datetime nowGmt = TimeGMT();
    int regionOffsetSec = isNY ? GetNYUtcOffsetSecondsAt(nowGmt) : GetLondonUtcOffsetSecondsAt(nowGmt);
    datetime regionNow = nowGmt + regionOffsetSec;
    MqlDateTime rd = ToDateStruct(regionNow);
    datetime regionTarget = FromDateParts(rd.year, rd.mon, rd.day, localHour, localMin, 0);
    datetime utcTarget = regionTarget - regionOffsetSec;
    int serverOffsetSec = GetServerUtcOffsetSeconds();
    return utcTarget + serverOffsetSec;
}

void ComputeSessionTimes(SessionState &st, bool isNY)
{
    int sh, sm, eh, em; bool ok1, ok2;
    int ch, cm; bool okCut = false;
    int th, tm; bool okStart = false;
    if(isNY)
    {
        ok1 = ParseHHMM(InpNewYorkRangeStartLocal, sh, sm);
        ok2 = ParseHHMM(InpNewYorkRangeEndLocal,   eh, em);
        okCut = (StringLen(InpNewYorkCutoffLocal) > 0) && ParseHHMM(InpNewYorkCutoffLocal, ch, cm);
        okStart = (StringLen(InpNewYorkTradeStartLocal) > 0) && ParseHHMM(InpNewYorkTradeStartLocal, th, tm);
    }
    else
    {
        ok1 = ParseHHMM(InpLondonRangeStartLocal, sh, sm);
        ok2 = ParseHHMM(InpLondonRangeEndLocal,   eh, em);
        okCut = (StringLen(InpLondonCutoffLocal) > 0) && ParseHHMM(InpLondonCutoffLocal, ch, cm);
        okStart = (StringLen(InpLondonTradeStartLocal) > 0) && ParseHHMM(InpLondonTradeStartLocal, th, tm);
    }
    if(!(ok1 && ok2)) return;
    st.sessionStart = RegionLocalTodayToServerTime(isNY, sh, sm);
    st.sessionEnd   = RegionLocalTodayToServerTime(isNY, eh, em);
    st.cutoffTime   = okCut ? RegionLocalTodayToServerTime(isNY, ch, cm) : 0;
    st.tradeStartTime = okStart ? RegionLocalTodayToServerTime(isNY, th, tm) : st.sessionEnd;
    st.orbComputed  = false;
}

//====================================================================
// Utilities: Symbol & Pip helpers
//====================================================================
double GetPipSize()
{
    string sym = _Symbol;
    int digits = (int)SymbolInfoInteger(sym, SYMBOL_DIGITS);
    double point = _Point;

    // Heuristics for common assets
    if(StringFind(sym, "JPY") >= 0)
        return 0.01;
    if(StringFind(sym, "XAU") >= 0 || StringFind(sym, "GOLD") >= 0)
        return 0.10; // common XAUUSD pip
    if(digits >= 3)
        return 10.0 * point; // most FX with fractional pips
    return point;
}

double PointsFromPips(double pips)
{
    double pipSize = GetPipSize();
    return pips * (pipSize / _Point);
}

double NormalizePrice(double price)
{
    int digits = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);
    return NormalizeDouble(price, digits);
}

double ClampToStep(double value, double step)
{
    if(step <= 0) return value;
    return MathFloor(value / step + 1e-9) * step;
}

double ComputeLotsForRisk(double stopDistancePrice)
{
    // stopDistancePrice in price units (e.g., 0.00123)
    if(stopDistancePrice <= 0.0) return 0.0;
    double equity = AccountInfoDouble(ACCOUNT_EQUITY);
    double riskMoney = equity * (InpRiskPerTradePercent / 100.0);

    double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
    double tickSize  = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
    double contractSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_CONTRACT_SIZE);
    if(tickValue <= 0 || tickSize <= 0 || contractSize <= 0)
        return 0.0;

    // Value per lot for given price move
    double ticks = stopDistancePrice / tickSize;
    double valuePerLot = ticks * tickValue; // value per 1 lot
    if(valuePerLot <= 0) return 0.0;

    double lots = riskMoney / valuePerLot;

    double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
    double maxLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
    double step   = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
    lots = MathMax(minLot, MathMin(maxLot, ClampToStep(lots, step)));
    return lots;
}

//====================================================================
// Indicators
//====================================================================
double GetMA(ENUM_TIMEFRAMES tf, int period, ENUM_MA_METHOD method, ENUM_APPLIED_PRICE price, int shift)
{
    double buffer[];
    if(CopyBuffer(iMA(_Symbol, tf, period, 0, method, price), 0, shift, 1, buffer) != 1)
        return EMPTY_VALUE;
    return buffer[0];
}

double GetATR(ENUM_TIMEFRAMES tf, int period, int shift)
{
    double buffer[];
    if(CopyBuffer(iATR(_Symbol, tf, period), 0, shift, 1, buffer) != 1)
        return EMPTY_VALUE;
    return buffer[0];
}

//====================================================================
// ORB calculation
//====================================================================
bool CalculateORB(datetime startServer, datetime endServer, double &orbHigh, double &orbLow)
{
    if(startServer == 0 || endServer == 0 || endServer <= startServer)
        return false;
    MqlRates rates[];
    int copied = CopyRates(_Symbol, PERIOD_M1, startServer, endServer, rates);
    if(copied <= 0)
        return false;
    orbHigh = -DBL_MAX;
    orbLow  = DBL_MAX;
    for(int i = 0; i < copied; ++i)
    {
        if(rates[i].high > orbHigh) orbHigh = rates[i].high;
        if(rates[i].low  < orbLow)  orbLow  = rates[i].low;
    }
    return (orbHigh > -DBL_MAX/2 && orbLow < DBL_MAX/2 && orbHigh > orbLow);
}

//====================================================================
// Drawing helpers
//====================================================================
void DrawHLine(const string name, double price, color col)
{
    if(!InpShowORBLevels) return;
    if(ObjectFind(0, name) == -1)
    {
        ObjectCreate(0, name, OBJ_HLINE, 0, 0, price);
        ObjectSetInteger(0, name, OBJPROP_COLOR, col);
        ObjectSetInteger(0, name, OBJPROP_STYLE, STYLE_DASH);
        ObjectSetInteger(0, name, OBJPROP_WIDTH, 1);
    }
    ObjectSetDouble(0, name, OBJPROP_PRICE, price);
}

//====================================================================
// Trade state helpers
//====================================================================
int CountOpenPositions()
{
    int total = PositionsTotal();
    int count = 0;
    for(int i = 0; i < total; ++i)
    {
        ulong ticket = PositionGetTicket(i);
        if(ticket <= 0) continue;
        if(!PositionSelectByTicket(ticket)) continue;
        if(PositionGetInteger(POSITION_MAGIC) == (long)InpMagicNumber &&
           PositionGetString(POSITION_SYMBOL) == _Symbol)
        {
            count++;
        }
    }
    return count;
}

bool HasOpenPositionByDirection(ENUM_POSITION_TYPE type)
{
    int total = PositionsTotal();
    for(int i = 0; i < total; ++i)
    {
        ulong ticket = PositionGetTicket(i);
        if(ticket <= 0) continue;
        if(!PositionSelectByTicket(ticket)) continue;
        if(PositionGetInteger(POSITION_MAGIC) == (long)InpMagicNumber &&
           PositionGetString(POSITION_SYMBOL) == _Symbol &&
           PositionGetInteger(POSITION_TYPE) == type)
        {
            return true;
        }
    }
    return false;
}

//====================================================================
// Risk & Drawdown monitoring
//====================================================================
void UpdateEquityStats()
{
    double eq = AccountInfoDouble(ACCOUNT_EQUITY);
    if(g_todayPeakEquity < 1e-6) g_todayPeakEquity = eq;
    g_todayPeakEquity = MathMax(g_todayPeakEquity, eq);
    g_todayMinEquity  = MathMin(g_todayMinEquity,  eq);

    // Daily DD halt
    double dailyDDPct = (g_todayPeakEquity > 0) ? 100.0 * (g_todayPeakEquity - eq) / g_todayPeakEquity : 0.0;
    if(!g_dailyHalt && InpDailyDrawdownPercent > 0 && dailyDDPct >= InpDailyDrawdownPercent)
    {
        g_dailyHalt = true;
        if(InpEnableAlerts) Alert("ORB: Daily drawdown limit reached. Halting trading for today.");
    }

    // Overall DD halt vs initial equity
    if(g_initialEquity <= 0.0) g_initialEquity = eq; // initialize lazily
    double overallDDPct = (g_initialEquity > 0) ? 100.0 * (g_initialEquity - eq) / g_initialEquity : 0.0;
    if(!g_overallHalt && InpOverallDrawdownPercent > 0 && overallDDPct >= InpOverallDrawdownPercent)
    {
        g_overallHalt = true;
        if(InpEnableAlerts) Alert("ORB: Overall drawdown limit reached. Halting trading.");
    }
}

void ResetDailyState()
{
    g_todayPeakEquity = AccountInfoDouble(ACCOUNT_EQUITY);
    g_todayMinEquity  = g_todayPeakEquity;
    g_dailyHalt = false;
    // Reset session states
    g_stateNY.orbComputed = false; g_stateNY.tradesTaken = 0; g_stateNY.lastTradeTime = 0; g_stateNY.orbHigh = 0; g_stateNY.orbLow = 0; g_stateNY.sessionStart = 0; g_stateNY.sessionEnd = 0; g_stateNY.cutoffTime = 0; g_stateNY.tradeStartTime = 0;
    g_stateLondon.orbComputed = false; g_stateLondon.tradesTaken = 0; g_stateLondon.lastTradeTime = 0; g_stateLondon.orbHigh = 0; g_stateLondon.orbLow = 0; g_stateLondon.sessionStart = 0; g_stateLondon.sessionEnd = 0; g_stateLondon.cutoffTime = 0; g_stateLondon.tradeStartTime = 0;
}

//====================================================================
// Entry filters
//====================================================================
bool PassesTrendFilter(bool isLong)
{
    if(InpMAPeriod <= 0) return true;
    double ma = GetMA(InpTrendTF, InpMAPeriod, InpMAMethod, InpMAPrice, 1);
    if(ma == EMPTY_VALUE) return true; // fail open
    double lastClose;
    double buffer[];
    if(CopyClose(_Symbol, InpTrendTF, 1, 1, buffer) == 1) lastClose = buffer[0];
    else lastClose = iClose(_Symbol, InpTrendTF, 1);
    if(isLong) return lastClose >= ma;
    return lastClose <= ma;
}

bool PassesVolumeFilter()
{
    if(!InpVolumeConfirmation) return true;
    long vol0 = (long)iVolume(_Symbol, PERIOD_CURRENT, 0);
    long vol1 = (long)iVolume(_Symbol, PERIOD_CURRENT, 1);
    return vol0 > vol1;
}

bool CooldownActive(const SessionState &st)
{
    if(InpCooldownMinutes <= 0) return false;
    if(st.lastTradeTime == 0) return false;
    datetime now = TimeCurrent();
    return (now - st.lastTradeTime) < (InpCooldownMinutes * 60);
}

//====================================================================
// Order placement
//====================================================================
bool PlaceTrade(bool isLong, double entryPrice, double stopPrice, double takeProfitPrice)
{
    double stopDist = MathAbs(entryPrice - stopPrice);
    double lots = ComputeLotsForRisk(stopDist);
    if(lots <= 0) return false;

    trade.SetExpertMagicNumber(InpMagicNumber);
    trade.SetDeviationInPoints(InpSlippagePoints);
    bool ok = false;
    if(isLong)
    {
        ok = trade.Buy(lots, _Symbol, entryPrice, stopPrice, takeProfitPrice);
    }
    else
    {
        ok = trade.Sell(lots, _Symbol, entryPrice, stopPrice, takeProfitPrice);
    }
    return ok;
}

//====================================================================
// Position management (BE + ATR trail)
//====================================================================
void ManageOpenPositions()
{
    int total = PositionsTotal();
    for(int i = 0; i < total; ++i)
    {
        ulong ticket = PositionGetTicket(i);
        if(ticket == 0) continue;
        if(!PositionSelectByTicket(ticket)) continue;
        if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
        if(PositionGetInteger(POSITION_MAGIC) != (long)InpMagicNumber) continue;

        ENUM_POSITION_TYPE type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
        double entry  = PositionGetDouble(POSITION_PRICE_OPEN);
        double sl     = PositionGetDouble(POSITION_SL);
        double tp     = PositionGetDouble(POSITION_TP);
        double price  = (type == POSITION_TYPE_BUY) ? SymbolInfoDouble(_Symbol, SYMBOL_BID)
                                                   : SymbolInfoDouble(_Symbol, SYMBOL_ASK);
        double risk = MathAbs(entry - sl);
        if(risk <= 0) continue;
        double rMultiple = (type == POSITION_TYPE_BUY) ? (price - entry) / risk : (entry - price) / risk;

        // Breakeven
        if(InpBreakevenAfterR > 0 && rMultiple >= InpBreakevenAfterR)
        {
            double bePrice = entry;
            if(type == POSITION_TYPE_BUY && (sl < bePrice))
            {
                trade.PositionModify(ticket, NormalizePrice(bePrice), tp);
            }
            else if(type == POSITION_TYPE_SELL && (sl > bePrice))
            {
                trade.PositionModify(ticket, NormalizePrice(bePrice), tp);
            }
        }

        // ATR trailing after threshold
        if(InpATRPeriod > 0 && InpATRMultiplier > 0 && rMultiple >= InpTrailStartAfterR)
        {
            double atr = GetATR(InpATRTimeframe, InpATRPeriod, 1);
            if(atr != EMPTY_VALUE && atr > 0)
            {
                if(type == POSITION_TYPE_BUY)
                {
                    double newSL = NormalizePrice(price - InpATRMultiplier * atr);
                    if(newSL > sl && newSL < price)
                        trade.PositionModify(ticket, newSL, tp);
                }
                else if(type == POSITION_TYPE_SELL)
                {
                    double newSL = NormalizePrice(price + InpATRMultiplier * atr);
                    if(newSL < sl && newSL > price)
                        trade.PositionModify(ticket, newSL, tp);
                }
            }
        }
    }
}

//====================================================================
// Breakout logic
//====================================================================
void TrySessionBreakout(SessionState &st, bool isNY)
{
    if(st.sessionStart == 0 || st.sessionEnd == 0) return;
    datetime now = TimeCurrent();

    // Before or within session: compute ORB progressively; After end: finalize if not computed
    if(!st.orbComputed && now >= st.sessionEnd)
    {
        double hi, lo; if(CalculateORB(st.sessionStart, st.sessionEnd, hi, lo))
        {
            st.orbHigh = hi; st.orbLow = lo; st.orbComputed = true;
            // Draw
            if(isNY)
            {
                DrawHLine("ORB_NY_HIGH", st.orbHigh, InpColorORBHighNY);
                DrawHLine("ORB_NY_LOW",  st.orbLow,  InpColorORBLowNY);
            }
            else
            {
                DrawHLine("ORB_LDN_HIGH", st.orbHigh, InpColorORBHighLondon);
                DrawHLine("ORB_LDN_LOW",  st.orbLow,  InpColorORBLowLondon);
            }
        }
    }

    if(!st.orbComputed) return; // need ORB first
    if(st.tradesTaken >= InpMaxTradesPerSession) return;
    if(CooldownActive(st)) return;
    if(g_dailyHalt || g_overallHalt) return;
    if(st.tradeStartTime > 0 && now < st.tradeStartTime) return; // before trade start
    if(st.cutoffTime > 0 && now >= st.cutoffTime) return; // no new entries after cutoff

    // Filters: ORB width and max SL
    double pipSize = GetPipSize();
    double orbWidthPips = (st.orbHigh - st.orbLow) / pipSize;
    if(InpMaxORBWidthPips > 0 && orbWidthPips > InpMaxORBWidthPips)
        return;

    double minBreakPoints = PointsFromPips(InpMinBreakoutDistancePips);
    double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
    double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

    bool canLong = InpAllowLongs && PassesTrendFilter(true) && PassesVolumeFilter();
    bool canShort = InpAllowShorts && PassesTrendFilter(false) && PassesVolumeFilter();

    // Long breakout
    if(canLong && !HasOpenPositionByDirection(POSITION_TYPE_BUY))
    {
        double trigger = st.orbHigh + minBreakPoints * _Point; // careful: PointsFromPips returns points, so convert back to price by * _Point
        // Actually PointsFromPips returns points count; price distance = points * _Point
        trigger = st.orbHigh + PointsFromPips(InpMinBreakoutDistancePips) * _Point; // ensuring price distance
        if(ask >= trigger)
        {
            double stop = st.orbLow;
            double stopPips = MathAbs(trigger - stop) / pipSize;
            if(InpMaxStopLossPips <= 0 || stopPips <= InpMaxStopLossPips)
            {
                double tp = trigger + (trigger - stop) * InpRiskRewardRatio;
                if(PlaceTrade(true, ask, NormalizePrice(stop), NormalizePrice(tp)))
                {
                    st.tradesTaken++;
                    st.lastTradeTime = now;
                    if(InpEnableAlerts) Alert("ORB: Long breakout executed (", (isNY?"NY":"London"), ") at ", DoubleToString(ask, (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS)));
                }
            }
        }
    }

    // Short breakout
    if(canShort && !HasOpenPositionByDirection(POSITION_TYPE_SELL))
    {
        double trigger = st.orbLow - PointsFromPips(InpMinBreakoutDistancePips) * _Point;
        if(bid <= trigger)
        {
            double stop = st.orbHigh;
            double stopPips = MathAbs(stop - trigger) / pipSize;
            if(InpMaxStopLossPips <= 0 || stopPips <= InpMaxStopLossPips)
            {
                double tp = trigger - (stop - trigger) * InpRiskRewardRatio;
                if(PlaceTrade(false, bid, NormalizePrice(stop), NormalizePrice(tp)))
                {
                    st.tradesTaken++;
                    st.lastTradeTime = now;
                    if(InpEnableAlerts) Alert("ORB: Short breakout executed (", (isNY?"NY":"London"), ") at ", DoubleToString(bid, (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS)));
                }
            }
        }
    }
}

//====================================================================
// Panel
//====================================================================
void RenderPanel()
{
    if(!InpShowPanel) { Comment(""); return; }
    double eq = AccountInfoDouble(ACCOUNT_EQUITY);
    double bal = AccountInfoDouble(ACCOUNT_BALANCE);
    double dailyDDPct = (g_todayPeakEquity > 0) ? 100.0 * (g_todayPeakEquity - eq) / g_todayPeakEquity : 0.0;
    double overallDDPct = (g_initialEquity > 0) ? 100.0 * (g_initialEquity - eq) / g_initialEquity : 0.0;
    string ny = StringFormat("NY: %s start %s cut %s | ORB: %s | Trades: %d", 
        TimeToString(g_stateNY.sessionStart, TIME_MINUTES) + "-" + TimeToString(g_stateNY.sessionEnd, TIME_MINUTES),
        g_stateNY.tradeStartTime > 0 ? TimeToString(g_stateNY.tradeStartTime, TIME_MINUTES) : (TimeToString(g_stateNY.sessionEnd, TIME_MINUTES)),
        g_stateNY.cutoffTime > 0 ? TimeToString(g_stateNY.cutoffTime, TIME_MINUTES) : "-",
        g_stateNY.orbComputed ? ("H=" + DoubleToString(g_stateNY.orbHigh, (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS)) + ", L=" + DoubleToString(g_stateNY.orbLow, (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS))) : "pending",
        g_stateNY.tradesTaken);
    string ldn = StringFormat("LDN: %s start %s cut %s | ORB: %s | Trades: %d", 
        TimeToString(g_stateLondon.sessionStart, TIME_MINUTES) + "-" + TimeToString(g_stateLondon.sessionEnd, TIME_MINUTES),
        g_stateLondon.tradeStartTime > 0 ? TimeToString(g_stateLondon.tradeStartTime, TIME_MINUTES) : (TimeToString(g_stateLondon.sessionEnd, TIME_MINUTES)),
        g_stateLondon.cutoffTime > 0 ? TimeToString(g_stateLondon.cutoffTime, TIME_MINUTES) : "-",
        g_stateLondon.orbComputed ? ("H=" + DoubleToString(g_stateLondon.orbHigh, (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS)) + ", L=" + DoubleToString(g_stateLondon.orbLow, (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS))) : "pending",
        g_stateLondon.tradesTaken);

    string flags = StringFormat("Halt(daily=%s, overall=%s) | Cooldowns(NY=%s, LDN=%s)",
        g_dailyHalt?"Y":"N", g_overallHalt?"Y":"N",
        CooldownActive(g_stateNY)?"Y":"N", CooldownActive(g_stateLondon)?"Y":"N");

    string msg;
    msg += StringFormat("ORB EA %s\n", _Symbol);
    msg += StringFormat("Bal: %.2f  Eq: %.2f\n", bal, eq);
    msg += StringFormat("DD: daily=%.2f%% (limit %.2f%%), overall=%.2f%% (limit %.2f%%)\n", dailyDDPct, InpDailyDrawdownPercent, overallDDPct, InpOverallDrawdownPercent);
    msg += ny + "\n" + ldn + "\n" + flags + "\n";
    Comment(msg);
}

//====================================================================
// EA lifecycle
//====================================================================
int OnInit()
{
    g_initialEquity = AccountInfoDouble(ACCOUNT_EQUITY);
    g_lastDayServer = (datetime)SeriesInfoInteger(_Symbol, PERIOD_D1, SERIES_LASTBAR_DATE);
    ResetDailyState();
    return(INIT_SUCCEEDED);
}

void OnDeinit(const int reason)
{
    Comment("");
}

void OnTick()
{
    // Day change detection on server time
    datetime lastBarD1 = (datetime)SeriesInfoInteger(_Symbol, PERIOD_D1, SERIES_LASTBAR_DATE);
    if(lastBarD1 != g_lastDayServer)
    {
        g_lastDayServer = lastBarD1;
        ResetDailyState();
    }

    UpdateEquityStats();

    // Recompute session windows daily or if not set
    if(InpEnableNewYorkSession && (g_stateNY.sessionStart == 0 || g_stateNY.sessionEnd == 0))
        ComputeSessionTimes(g_stateNY, true);
    if(InpEnableLondonSession && (g_stateLondon.sessionStart == 0 || g_stateLondon.sessionEnd == 0))
        ComputeSessionTimes(g_stateLondon, false);

    // Run breakout checks
    if(InpEnableNewYorkSession)  TrySessionBreakout(g_stateNY, true);
    if(InpEnableLondonSession)   TrySessionBreakout(g_stateLondon, false);

    // Manage open positions
    ManageOpenPositions();

    // Render panel
    RenderPanel();
}

//====================================================================
// Notes:
// - Session inputs are interpreted as local times for New York and London.
//   The EA converts them to broker server time using built-in UTC and DST logic
//   approximations for those regions. Verify on your broker and adjust if needed.
// - Risk sizing uses tick value/size. For exotic symbols, validate pip assumptions.
// - Place EA on a chart and ensure algo trading is enabled.
//====================================================================

